---
- name: create vm 
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_files:
    - vars.yml
  
  tasks:
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "poweredon"
        guest_id: "{{ vm_guestid }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_num }}"
        customization:
          password: "VMware123!"
          hostname: "VMTest123"
        networks:
        - name: "{{ vm_net_name }}"
          device_type: "{{ vm_net_type }}"
          type: static
          ip: "{{ vm_ip }}"
          netmask: "{{ vm_net_mask }}"
          gateway: "{{ vm_net_gw }}"
          dns_servers: "{{ vm_net_dns }}"
          start_connected: yes
        wait_for_ip_address: true
        
